name: lanefocus
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  get: ^4.6.5
  pinput: ^4.0.0
  ripple_wave: ^0.1.3
  smooth_page_indicator: ^1.1.0
  flutter_holo_date_picker: ^1.1.3
  dropdown_button2: ^2.3.9
  syncfusion_flutter_charts: ^24.2.9
  percent_indicator: ^4.2.3
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  geolocator: ^12.0.0
  geoflutterfire_plus: ^0.0.24
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.6
  google_sign_in: ^6.2.1
  file_picker: ^8.0.6
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  app_settings: ^5.1.1
  firebase_messaging: ^15.0.2
  flutter_local_notifications: ^17.2.1
  googleapis_auth: ^1.6.0
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1
  firebase_dynamic_links: ^6.0.2
  intl_phone_field: ^3.2.0
  flutter_contacts: ^1.1.8
  # Network check
  connectivity_plus: ^5.0.2

  share_plus: ^9.0.0
  uuid: ^4.4.0

  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^2.1.0
  location: ^7.0.0

  app_usage: ^3.0.1
  usage_stats: ^1.2.0
  intl: ^0.19.0


  timeago: ^3.7.0



dev_dependencies:

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: splineSans
      fonts:
        - asset: assets/fonts/spline_sans/SplineSans-Light.ttf
          weight: 300
        - asset: assets/fonts/spline_sans/SplineSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/spline_sans/SplineSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/spline_sans/SplineSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/spline_sans/SplineSans-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""
