// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBToPYmcDZlf7adITLXNs36mbPE0jD2hF8',
    appId: '1:80912705747:web:755bd08202444c1db88c26',
    messagingSenderId: '80912705747',
    projectId: 'lanefocusflutter',
    authDomain: 'lanefocusflutter.firebaseapp.com',
    storageBucket: 'lanefocusflutter.appspot.com',
    measurementId: 'G-XRBNXFNSXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOoZk-olO2ufzRQra1T9RLzzDNALlYSLs',
    appId: '1:80912705747:android:39bdb84316901e00b88c26',
    messagingSenderId: '80912705747',
    projectId: 'lanefocusflutter',
    storageBucket: 'lanefocusflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJCCQ_-VzX-hmWV9ds2MByQzOfQtrs0KM',
    appId: '1:80912705747:ios:efb8f0acadbcbff8b88c26',
    messagingSenderId: '80912705747',
    projectId: 'lanefocusflutter',
    storageBucket: 'lanefocusflutter.appspot.com',
    iosClientId: '80912705747-1un452c6eh3bpeli4lmbq4fgjmfr2314.apps.googleusercontent.com',
    iosBundleId: 'com.example.lanefocus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJCCQ_-VzX-hmWV9ds2MByQzOfQtrs0KM',
    appId: '1:80912705747:ios:efb8f0acadbcbff8b88c26',
    messagingSenderId: '80912705747',
    projectId: 'lanefocusflutter',
    storageBucket: 'lanefocusflutter.appspot.com',
    iosClientId: '80912705747-1un452c6eh3bpeli4lmbq4fgjmfr2314.apps.googleusercontent.com',
    iosBundleId: 'com.example.lanefocus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBToPYmcDZlf7adITLXNs36mbPE0jD2hF8',
    appId: '1:80912705747:web:6066a624e9654ed2b88c26',
    messagingSenderId: '80912705747',
    projectId: 'lanefocusflutter',
    authDomain: 'lanefocusflutter.firebaseapp.com',
    storageBucket: 'lanefocusflutter.appspot.com',
    measurementId: 'G-0Z4B3FTDSG',
  );

}